### ISSUE TITLE
Unable to install the package

### ISSUE THREAD

**Issue by ziotom78** [SuperKam91/gns#1]
The README says that the following command should be enough to install the package, yet it fails:

```
$ pip install GNS==1.0
ERROR: Could not find a version that satisfies the requirement GNS==1.0 (from versions: none)
ERROR: No matching distribution found for GNS==1.0
```

(I was trying to install the package to perform the [review](https://github.com/openjournals/joss-reviews/issues/1809) for the JOSS.)

**Comment by SuperKam91** [comment]
> The README says that the following command should be enough to install the package, yet it fails:
> 
> ```
> $ pip install GNS==1.0
> ERROR: Could not find a version that satisfies the requirement GNS==1.0 (from versions: none)
> ERROR: No matching distribution found for GNS==1.0
> ```
> 
> (I was trying to install the package to perform the [review](https://github.com/openjournals/joss-reviews/issues/1809) for the JOSS.)

Hi @ziotom78 thank you for your message. That is very odd, I just tried `pip installing` the package on a machine which has never had the package, and it seemed to work fine.
![Screenshot from 2019-10-15 00-00-59](https://user-images.githubusercontent.com/25101227/66788313-104b5180-eedf-11e9-9931-5727ac44d62d.png)

Perhaps try `pip install GNS` instead? Lemme know how you get on.

**Comment by ziotom78** [comment]
Mmm… I think I spotted the problem. I am running Python 3.7; does this package require Python 2.7?

**Comment by SuperKam91** [comment]
> Mmm… I think I spotted the problem. I am running Python 3.7; does this package require Python 2.7?

HI @ziotom78 yes thanks for spotting this. I just realised the `wheel` file I built and put on PyPi is a `py2`. I developed and tested the code using `python 2.7` so I recommend using that version when using the algorithm. I have edited the `README` and `setup.py` accordingly.

**Comment by ziotom78** [comment]
Are you really sure you want to publish a library that requires a version of Python that in a few weeks will be [deprecated and no longer maintained](https://pythonclock.org/)?

**Comment by ziotom78** [comment]
I was able to build a Singularity container to run Python 2.7, as my system (Linux Manjaro) does no longer supports it. However, `pip` fails:

```
$ singularity exec python2.sif sh
Singularity> pip install GNS==1.0
Collecting GNS==1.0
  Downloading https://files.pythonhosted.org/packages/62/55/1cec82e159e361e765563e6094795269e0406f48ea347a9ac17f000270de/GNS-1.0-py2-none-any.whl (83kB)
    100% |################################| 92kB 2.6MB/s 
Collecting scipy (from GNS==1.0)
  Downloading https://files.pythonhosted.org/packages/ee/5b/5afcd1c46f97b3c2ac3489dbc95d6ca28eacf8e3634e51f495da68d97f0f/scipy-1.3.1.tar.gz (23.6MB)
    100% |################################| 23.6MB 79kB/s 
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-blvcH3/scipy/setup.py", line 31, in <module>
        raise RuntimeError("Python version >= 3.5 required.")
    RuntimeError: Python version >= 3.5 required.
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-blvcH3/scipy/
You are using pip version 8.1.1, however version 19.3 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```

The problem lies in the fact you did not specify version numbers for the dependencies in `requirements.txt`, and the latest version of `scipy` no longer works with Python2. Therefore, when `pip` tries to install the dependencies, it fails. On your system nothing happens because you probably have an old version of `numpy` and `scipy`.

I reiterate my suggestion: you should really consider converting this package to Python3. It is not very difficult, most of the process can be automatized using `2to3`. It will be available to a much wider audience.

**Comment by SuperKam91** [comment]
> I was able to build a Singularity container to run Python 2.7, as my system (Linux Manjaro) does no longer supports it. However, `pip` fails:
> 
> ```
> $ singularity exec python2.sif sh
> Singularity> pip install GNS==1.0
> Collecting GNS==1.0
>   Downloading https://files.pythonhosted.org/packages/62/55/1cec82e159e361e765563e6094795269e0406f48ea347a9ac17f000270de/GNS-1.0-py2-none-any.whl (83kB)
>     100% |################################| 92kB 2.6MB/s 
> Collecting scipy (from GNS==1.0)
>   Downloading https://files.pythonhosted.org/packages/ee/5b/5afcd1c46f97b3c2ac3489dbc95d6ca28eacf8e3634e51f495da68d97f0f/scipy-1.3.1.tar.gz (23.6MB)
>     100% |################################| 23.6MB 79kB/s 
>     Complete output from command python setup.py egg_info:
>     Traceback (most recent call last):
>       File "<string>", line 1, in <module>
>       File "/tmp/pip-build-blvcH3/scipy/setup.py", line 31, in <module>
>         raise RuntimeError("Python version >= 3.5 required.")
>     RuntimeError: Python version >= 3.5 required.
>     
>     ----------------------------------------
> Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-blvcH3/scipy/
> You are using pip version 8.1.1, however version 19.3 is available.
> You should consider upgrading via the 'pip install --upgrade pip' command.
> ```
> 
> The problem lies in the fact you did not specify version numbers for the dependencies in `requirements.txt`, and the latest version of `scipy` no longer works with Python2. Therefore, when `pip` tries to install the dependencies, it fails. On your system nothing happens because you probably have an old version of `numpy` and `scipy`.
> 
> I reiterate my suggestion: you should really consider converting this package to Python3. It is not very difficult, most of the process can be automatized using `2to3`. It will be available to a much wider audience.

Thank you for the suggestion @ziotom78, I have now made it `python 3.X` compatible and tested it using `python 3.6`. FYI, `pip install` isn't using `requirements.txt` in your code snippet, it is using the `install_requires` value in `setup.py`. `requirements.txt` is used when installing the package using the second method in the `README`.

**Comment by ziotom78** [comment]
Great, now it works!
