### ISSUE TITLE
Missing examples and documentation

### ISSUE THREAD

**Issue by ziotom78** [SuperKam91/gns#2]
The only documentation for the library seems to be in `tests`. Ideally, one would expect a short example to be included in the `README`. A nice example is the following package, which has been positively reviewed by JOSS referees:

    https://github.com/GeoStat-Framework/pentapy

**Comment by ziotom78** [comment]
Another missing point is some API documentation. This should include a list of functions, grouped by category, a list of arguments, the return value, and a description of their purpose.

Today, Python packages are usually documented using Sphinx, and the documentation is hosted either on [ReadTheDocs](https://readthedocs.org/) or [GitHub pages](https://pages.github.com/). You can refer to `pentapy` again:

    https://geostat-framework.readthedocs.io/projects/pentapy/en/latest/

**Comment by ziotom78** [comment]
This refers to JOSS' review («Functionality documentation», https://github.com/openjournals/joss-reviews/issues/1809).

**Comment by SuperKam91** [comment]
Thank you again @ziotom78 for your advice. I have taken your comments on board and created a `read the docs` site for gns: `https://geometric-nested-sampling.readthedocs.io/en/latest/`.

It's a little rough round the edges, but hopefully it will suffice for now and I will refine it over time as I learn how to use `sphinx` better. Note the main sub-modules which would be used by the end user, i.e. `nested_run.py`, `plotting.py`, `output.py` and `theoretical_funcs.py` have been documented the most. 

I have included a minimum working example in both the `README` and the `read the docs` pages.

**Comment by ziotom78** [comment]
Excellent! However, the documentation refers to file `PACKAGEAPI.md` for the full documentation of the API, yet this file does not exist in the repository. Did you forget to add it to the commit?

**Comment by SuperKam91** [comment]
@ziotom78 good spot. I have rectified this typo, the API documentation should now be live: https://geometric-nested-sampling.readthedocs.io/en/latest/index.html. As I said above, may need tidying up in a few places but hopefully will be sufficient in its current form.
